### ISSUE TITLE
Ignoring built-in annotations

### ISSUE THREAD

**Issue by jmoney8080** [FasterXML/jackson-dataformat-avro#25] opened 2015-11-11 22:09 UTC
In using this it seems the mapper is ignoring standard annotations that comes with avro.  Fields marked with AvroIgnore are not ignored and it seems everything unions with null making the nullable annotation useless in the schema generation.  Those are the two big ones I've witnessed but I'm sure the others do not work either.

**Comment by jmonette** [comment] 2015-11-11 22:18
Here is a test proving that the process is ignoring @AvroIgnore: https://github.com/jmonette/jackson-dataformat-avro/commit/2c35da63f8a66f02bc4411a5e462c40e6dacc4b1

This test is hung off of master.

**Comment by cowtowncoder** [comment] 2015-11-12 02:06
We are not making any use of Avro annotations at dataformat level, so this is not a bug per se but something that is currently out of scope. Module only supports streaming-level encoding and decoding support, which does not work at databinding level; similar to how `jackson-core` itself does not do anything with Jackson annotations.

But the follow-up questions would be:

1. Is there interest in adding support for Avro-generated Java classes, and if so,
2. Where should the `AnnotationIntrospector` be added that would consider Avro annotations.

Adding such introspector, similar to `jackson-module-jaxb-annotations` which can be used to use JAXB annotations, should be quite simple. And I guess that would suggest possibility of `jackson-module-avro-annotations` module.
At the same time, it would be just one additional class, so perhaps that'd be an overkill, and we should instead just implement it in this package, and perhaps even make `AvroMapper` add it by default, along with Jackson default introspector.

**Comment by jmoney8080** [comment] 2015-11-12 03:16
So implementing a annotation introspector is how I got AvroIgnore working. I guess I can use the same pattern to do the other pattern now that I think about it. 

The one thing it doesn't solve though is billable. Currently generating a schema unions every field with null but there is no mechanism for specifying the field in the generated schema as not null. Avro provides an annotation for specifying a field as nullable which will do the union with null. 

So my question is, do you think the generator should not union with null for all fields and process the nullable annotation when present as Avro provides or should there be another annotation(or process javax NotNull) to not Union the field with null?

**Comment by cowtowncoder** [comment] 2015-11-12 03:52
This is a tricky part of Avro Schemas, but it should be possible to specify `@JsonProperty(required=true)` to remove nullability. Use of `javax.NotNull` could work, depending on where it comes from; with Jackson 2.7 baseline will be Java 7, but otherwise we try to avoid adding dependencies beyond JDK.
However, custom `AnnotationIntrospector` could easily add other sources of "requiredness"; method to override is `hasRequiredMarker()`.

**Comment by cowtowncoder** [comment] 2016-05-06 02:23
Moved to https://github.com/FasterXML/jackson-dataformats-binary/issues/10

**Closed by cowtowncoder** 2016-05-06 02:23 UTC
