### ISSUE TITLE
Not able to serialize avro generated object having schema$ object

### ISSUE THREAD

**Issue by anandshah123** [FasterXML/jackson-dataformat-avro#35] opened 2016-02-18 15:35 UTC
Below exception is thrown

```
com.fasterxml.jackson.databind.JsonMappingException: No field named 'schema' (through reference chain: com.demonstration.Event["schema"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:339)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:299)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:342)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:686)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1428)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1129)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsBytes(ObjectWriter.java:1025)
	at com.fasterxml.jackson.dataformat.avro.WriteGeneratedObject.testWriteBidResponse(WriteGeneratedObject.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: No field named 'schema'
	at com.fasterxml.jackson.dataformat.avro.ser.ObjectWriteContext._reportUnknownField(ObjectWriteContext.java:124)
	at com.fasterxml.jackson.dataformat.avro.ser.ObjectWriteContext.writeFieldName(ObjectWriteContext.java:67)
	at com.fasterxml.jackson.dataformat.avro.AvroGenerator.writeFieldName(AvroGenerator.java:283)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:670)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	... 25 more

```

**Comment by cowtowncoder** [comment] 2016-02-22 03:31
Which Jackson version is this with?

**Comment by anandshah123** [comment] 2016-02-22 14:47
I am getting this for any version above 2.4.3 but theoretically it should happen for all versions. 
Probable reason is that `BeanSerializer` identifies `SCHEMA$` as field (even if it is static)

**Comment by cowtowncoder** [comment] 2016-02-22 20:25
@anandshah123 `static` members should not be included, although I vaguely recall fixing a bug in that handling a while ago. But that would probably have been before 2.4.3.

I think I better have a look at your test case at this point.

**Comment by anandshah123** [comment] 2016-03-06 21:24
https://github.com/anandshah123/jackson-dataformat-avro/blob/72402467d46430a1e0146793d4bbb9b5f19d40d6/src/test/java/com/fasterxml/jackson/dataformat/avro/Issue35Test.java

**Comment by cowtowncoder** [comment] 2016-03-09 03:36
Ok; the problem is not the static field, but rather definition in `SpecificRecordBase`:

```java
public abstract class SpecificRecordBase
  implements SpecificRecord, Comparable<SpecificRecord>, GenericRecord {

  public abstract Schema getSchema();
}
```

which does suggest there is property `schema`, accessible via `getSchema()`.
I'll have to think about how to handle this.

In the meantime, you can work around this by adding mix-in for something like

```java
abstract class Mixin {
   @JsonIgnore
   public abstract Schema getSchema();
}
```

and attach that to `SpecificRecordBase`. That should get rid of the property for all generated types.

**Comment by cowtowncoder** [comment] 2016-03-09 05:17
@anandshah123 I think this could be fixed via `AvroModule` registering `BeanSerializerModifier`, which would strip `schema` property. I'll add a failing test first.

**Comment by cowtowncoder** [comment] 2016-03-09 05:50
Fixed this. Note: you need to use `AvroMapper` to get functionality (or if you really want to, register `AvroSerializerModifier` via custom module).

**Closed** 2016-03-09 05:49 UTC
